version: '3.8'
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    depends_on:
      ray-head:
        condition: service_healthy
    env_file:
      - ../grafana/grafana.env
    ports:
      - '3000:3000'
    volumes:
      - grafana_storage:/var/lib/grafana
      - ray_dashboard:/tmp/ray/:rw
    networks:
      - ray_net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    depends_on:
      ray-head:
        condition: service_healthy
    user: root
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ../prometheus:/etc/prometheus
      - prom_data:/prometheus
      - ray_dashboard:/tmp/ray/:rw
    networks:
      - ray_net

  ray-head:
    build:
          context: .
          dockerfile: ./Dockerfile.ray
    environment:
      - RAY_GRAFANA_HOST=http://grafana:3000
      - RAY_PROMETHEUS_HOST=http://prometheus:9090
      - RAY_GRAFANA_IFRAME_HOST=http://localhost:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8265"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 40s
    user: root
    ports:
      - "8265:8265"
      - "10001:10001"
      - "8081:8081"
    command: bash -c "ray start --head --dashboard-port=8265 --port=8365 --dashboard-host=0.0.0.0 --redis-password=admin --metrics-export-port=8081 --block"
    shm_size: 2g
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2g'
    volumes:
      - ray_dashboard:/tmp/ray/:rw
    networks:
      - ray_net

  ray-worker:
    build:
          context: .
          dockerfile: ./Dockerfile.ray
    user: root
    depends_on:
      - ray-head
    command: bash -c "ray start --address=ray-head:8365 --redis-password=admin --num-cpus=1 --block"
    shm_size: 2g
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: '2g'
    networks:
      - ray_net

volumes:
  grafana_storage:
  grafana:
  prom_data:
  ray_dashboard:

networks:
  ray_net:
    ipam:
      driver: default
      config:
        - subnet: 172.63.0.0/16
