FROM rayproject/ray:2.9.2 as base

USER root
RUN apt-get update \ 
    && apt-get install -y --no-install-recommends \
    vim \
    gcc \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* 
COPY ./requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r ./requirements.txt